# Nexus User Preferences
# Customize these to fit your workflow preferences

# Your preferred default workflow
# Options: feature-full, feature-quick, bugfix, refactor, code-review
default_workflow: "feature-quick"

# Plugin preferences
plugins:
  ald:
    always_use_policies: true
    auto_curator: true

  superpowers:
    skip_brainstorm_for_simple_tasks: true

# Workflow customizations
workflows:
  feature-full:
    skip_phases: []  # Don't skip any phases

  feature-quick:
    skip_phases: []

  bugfix:
    skip_phases: ["brainstorm", "planning"]  # Fast bugfixes

  refactor:
    skip_phases: []

# Personal preferences
preferences:
  confirm_before_execute: true
  show_progress_updates: true
  detailed_error_messages: true
